services:
  api-example:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-example
    environment:
      - DB_HOST=pg-example
      - REDIS_HOST=redis-example
    depends_on:
      - pg-example
      - redis-example
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8002:8002"
    restart: always

  pg-example:
    image: postgres:17-alpine
    container_name: pg-example
    environment:
      - POSTGRES_USER=marcus
      - POSTGRES_PASSWORD=marcus
      - POSTGRES_DB=application
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: always

  redis-example:
    image: redis:8-alpine
    container_name: redis-example
    ports:
      - "127.0.0.1:6379:6379"
    restart: always

volumes:
  postgres_data:

networks:
  default:
    name: api-example-network
